---
- name: Allow traffic to minio through firewall (firewalld)
  firewalld:
    port: "{{ item.bind_port }}/tcp"
    state: enabled
    zone: public
    immediate: yes
    permanent: yes
  with_items: "{{ minio_instances }}"
  when: ansible_os_family == 'RedHat'
- name: Allow traffic to minio through firewall (ufw)
  ufw:
    to_port: "{{ item.bind_port }}"
    proto: tcp
    rule: allow
    state: reloaded
  with_items: "{{ minio_instances }}"
  when: ansible_os_family == 'Debian'
...
