---
- name: Allow traffic to minio through firewall
  firewalld:
    port: "{{ item.bind_port }}/tcp"
    state: enabled
    zone: public
    immediate: yes
    permanent: yes
  with_items: "{{ minio_instances }}"
...
