---
- name: Copy systemd unit file
  template:
    src: minio-systemd-unit.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
  notify: reload_systemd
- name: Enable minio service
  service:
    name: minio
    state: started
    enabled: yes
...
